import { invoke } from "@tauri-apps/api/core";
import type { AgentDef, WindowInfo, AgentMessage, ChatMessage, WarRoomState, TranscriptEntry, SpiderlingDef, Objective } from "../types";

export const commands = {
  tmuxCreateSession: (sessionName: string) => invoke<string>("tmux_create_session", { sessionName }),
  tmuxListWindows: (sessionName: string) => invoke<WindowInfo[]>("tmux_list_windows", { sessionName }),
  tmuxCreateWindow: (sessionName: string, windowName: string) => invoke<string>("tmux_create_window", { sessionName, windowName }),
  tmuxKillWindow: (windowId: string) => invoke<void>("tmux_kill_window", { windowId }),
  tmuxSelectWindow: (windowId: string) => invoke<void>("tmux_select_window", { windowId }),
  tmuxRenameWindow: (target: string, newName: string) => invoke<void>("tmux_rename_window", { target, newName }),
  startPty: (sessionName: string) => invoke<void>("start_pty", { sessionName }),
  writePty: (input: string) => invoke<void>("write_pty", { input }),
  resizePty: (rows: number, cols: number) => invoke<void>("resize_pty", { rows, cols }),
  startAgent: (name: string) => invoke<void>("start_agent", { name }),
  stopAgent: (name: string) => invoke<void>("stop_agent", { name }),
  listAgents: () => invoke<AgentDef[]>("list_agents"),
  updateAgentModel: (name: string, model: string) => invoke<void>("update_agent_model", { name, model }),
  getRecentMessages: () => invoke<AgentMessage[]>("get_recent_messages"),
  clearMessageHistory: () => invoke<void>("clear_message_history"),
  clearConversationHistory: (agentA: string, agentB: string) => invoke<void>("clear_conversation_history", { agentA, agentB }),
  sendChat: (toAgent: string, message: string) => invoke<void>("send_chat", { toAgent, message }),
  getChatMessages: () => invoke<ChatMessage[]>("get_chat_messages"),
  clearChatHistory: () => invoke<void>("clear_chat_history"),
  createWarroom: (topic: string, participants: string[]) => invoke<void>("create_warroom", { topic, participants }),
  getWarroomState: () => invoke<WarRoomState | null>("get_warroom_state"),
  getWarroomTranscript: () => invoke<TranscriptEntry[]>("get_warroom_transcript"),
  warroomInterject: (message: string) => invoke<void>("warroom_interject", { message }),
  warroomSkip: () => invoke<void>("warroom_skip"),
  warroomConclude: () => invoke<void>("warroom_conclude"),
  warroomCancel: () => invoke<void>("warroom_cancel"),
  warroomInviteParticipant: (name: string) => invoke<void>("warroom_invite_participant", { name }),
  listWarroomHistory: () => invoke<WarRoomState[]>("list_warroom_history"),
  getWarroomHistoryTranscript: (id: string) => invoke<TranscriptEntry[]>("get_warroom_history_transcript", { id }),
  listSpiderlings: () => invoke<SpiderlingDef[]>("list_spiderlings"),
  killSpiderling: (name: string) => invoke<void>("kill_spiderling_cmd", { name }),
  listBeadsTasks: () => invoke<any>("list_beads_tasks"),
  updateBeadsTaskStatus: (taskId: string, status: string) => invoke<void>("update_beads_task_status", { taskId, status }),
  listObjectives: () => invoke<Objective[]>("list_objectives"),
  createObjective: (title: string, description: string, priority: number) => invoke<Objective>("create_objective", { title, description, priority }),
  updateObjective: (id: string, fields: { title?: string; description?: string; spec?: string; status?: string; priority?: number; task_ids?: string[] }) =>
    invoke<Objective>("update_objective", { id, ...fields }),
  deleteObjective: (id: string) => invoke<void>("delete_objective", { id }),
  openFile: (path: string) => invoke<void>("open_file", { path }),
};
